name: ubuntu-clang

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CC: clang-18
  CXX: clang++-18
  CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: clang-scan-deps-18

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build

      - name: Install Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt install clang-tools-18

      - name: Check versions
        run: |
          echo "======================================================="
          echo "================ CMAKE version ========================"
          cmake --version
          echo "================ Ninja version ========================"
          ninja --version
          echo "================ GCC version =========================="
          gcc --version
          echo "================ Clang version ========================"
          clang-19 --version
          echo "================ Clang++ version ======================"
          clang++-19 --version
          echo "================ Clang scan-deps version =============="
          clang-scan-deps-19 --version
          echo "================ GCOV (llvm-cov) version =============="
          llvm-cov --version
          echo "======================================================="

      - name: Configure CMake
        run: cmake -S . -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config Release

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest --extra-verbose
