name: ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CC: clang-18
  CXX: clang++-18

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install clang (18>=) & ninja (1.11>=)
        run: |
          sudo apt update
          echo Update ninja =======================================================================
          echo ninja version before
          ninja --version
          # wget https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-linux.zip
          wget https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
          sudo unzip ninja-linux.zip -d /usr/local/bin/
          sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force
          echo ninja version after
          ninja --version
          echo Update Clang =======================================================================
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        shell: bash

      - name: Check cmake
        run: cmake --version

      - name: Configure CMake
        run: cmake -G Ninja -S . -B ${{runner.workspace}}/build

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake -G Ninja --build . --target ALL_BUILD --config Release

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V
