name: ubuntu-clang

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CC: clang-19
  CXX: clang++-19
  CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: clang-scan-deps-19

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip build-essential
          sudo apt-get install -y cmake ninja-build
          sudo apt-get install -y libc++-dev libc++abi-dev

      - name: Install CMake
        run: |
          cmake_version=$(curl --silent "https://api.github.com/repos/Kitware/CMake/releases/latest" | sed -n 's/.*tag_name":\s"\(.*\)".*/\1/p' | head -2 | cut -c 2-)
          wget https://github.com/Kitware/CMake/releases/download/v$cmake_version/cmake-$cmake_version-Linux-x86_64.sh
          chmod +x cmake-$cmake_version-Linux-x86_64.sh
          sudo mkdir /opt/cmake
          sudo ./cmake-$cmake_version-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
          sudo update-alternatives --install /usr/bin/cmake cmake /opt/cmake/bin/cmake 1 --force
          sudo update-alternatives --install /usr/bin/ctest ctest /opt/cmake/bin/ctest 1 --force

      - name: Install Ninja
        run: |
          wget https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
          sudo unzip ninja-linux.zip -d /usr/local/bin/
          sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force

      - name: Install Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          sudo update-alternatives --install /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-19 1 --force
          sudo apt install clang-tools-19
          # sudo update-alternatives --install /usr/bin/clang-scan-deps-19 clang-scan-deps-19 /usr/bin/clang-scan-deps-19 1 --force

      - name: Check versions
        run: |
          echo "======================================================="
          echo "================ CMAKE version ========================"
          cmake --version
          echo "================ Ninja version ========================"
          ninja --version
          echo "================ Clang version ========================"
          clang-19 --version
          echo "================ Clang++ version ======================"
          clang++-19 --version
          echo "================ Clang scan-deps version =============="
          clang-scan-deps-19 --version
          echo "================ GCOV (llvm-cov) version =============="
          llvm-cov --version
          echo "======================================================="

      - name: Configure CMake
        run: cmake -S . -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config Release

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest --extra-verbose
