name: ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CC: clang
  CXX: clang++

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Install clang
        run: |
          sudo apt update
          bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        shell: bash

      - name: Check cmake
        run: cmake --version

      - name: Configure CMake
        run: cmake -S . -B ${{runner.workspace}}/build

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --target ALL_BUILD --config Release

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V
