name: windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GTEST_OUTPUT: xml:test-results/
  GTEST_COLOR: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check cmake
        run: cmake --version

      - name: Configure CMake
        run: cmake -S . -B ${{runner.workspace}}/build

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --target ALL_BUILD --config Debug

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest -V
